# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'image_rescale.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 496)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("assets/resize_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(
            QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates)
        )
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveButton.sizePolicy().hasHeightForWidth())
        self.saveButton.setSizePolicy(sizePolicy)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 1, 6, 1, 1)
        self.heightLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heightLabel.sizePolicy().hasHeightForWidth())
        self.heightLabel.setSizePolicy(sizePolicy)
        self.heightLabel.setObjectName("heightLabel")
        self.gridLayout.addWidget(self.heightLabel, 4, 2, 1, 1)
        self.widthLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widthLabel.sizePolicy().hasHeightForWidth())
        self.widthLabel.setSizePolicy(sizePolicy)
        self.widthLabel.setObjectName("widthLabel")
        self.gridLayout.addWidget(self.widthLabel, 4, 0, 1, 1)
        self.widthEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widthEdit.sizePolicy().hasHeightForWidth())
        self.widthEdit.setSizePolicy(sizePolicy)
        self.widthEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.widthEdit.setObjectName("widthEdit")
        self.gridLayout.addWidget(self.widthEdit, 4, 1, 1, 1)
        self.inputFileEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.inputFileEdit.setLocale(
            QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates)
        )
        self.inputFileEdit.setObjectName("inputFileEdit")
        self.gridLayout.addWidget(self.inputFileEdit, 1, 0, 1, 5)
        self.heightEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heightEdit.sizePolicy().hasHeightForWidth())
        self.heightEdit.setSizePolicy(sizePolicy)
        self.heightEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.heightEdit.setObjectName("heightEdit")
        self.gridLayout.addWidget(self.heightEdit, 4, 3, 1, 1)
        self.imageScrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.imageScrollArea.setMinimumSize(QtCore.QSize(0, 300))
        self.imageScrollArea.viewport().setProperty(
            "cursor", QtGui.QCursor(QtCore.Qt.OpenHandCursor)
        )
        self.imageScrollArea.setStyleSheet("")
        self.imageScrollArea.setLocale(
            QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates)
        )
        self.imageScrollArea.setWidgetResizable(True)
        self.imageScrollArea.setObjectName("imageScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 704, 372))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.imageLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.imageLabel.setText("")
        self.imageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        self.gridLayout_2.addWidget(self.imageLabel, 0, 0, 1, 1)
        self.imageScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.imageScrollArea, 0, 0, 1, 7)
        self.resizeButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resizeButton.sizePolicy().hasHeightForWidth())
        self.resizeButton.setSizePolicy(sizePolicy)
        self.resizeButton.setStyleSheet(
            "* {\n" "    background-color: green;\n" "    color: white;\n" "}"
        )
        self.resizeButton.setObjectName("resizeButton")
        self.gridLayout.addWidget(self.resizeButton, 4, 6, 1, 1)
        self.inputFileButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.inputFileButton.sizePolicy().hasHeightForWidth()
        )
        self.inputFileButton.setSizePolicy(sizePolicy)
        self.inputFileButton.setLocale(
            QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates)
        )
        self.inputFileButton.setObjectName("inputFileButton")
        self.gridLayout.addWidget(self.inputFileButton, 1, 5, 1, 1)
        self.ratioCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.ratioCheckBox.setObjectName("ratioCheckBox")
        self.gridLayout.addWidget(self.ratioCheckBox, 4, 4, 1, 2)
        self.saveButton.raise_()
        self.heightLabel.raise_()
        self.widthLabel.raise_()
        self.widthEdit.raise_()
        self.inputFileEdit.raise_()
        self.imageScrollArea.raise_()
        self.resizeButton.raise_()
        self.inputFileButton.raise_()
        self.ratioCheckBox.raise_()
        self.heightEdit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.inputFileEdit, self.inputFileButton)
        MainWindow.setTabOrder(self.inputFileButton, self.widthEdit)
        MainWindow.setTabOrder(self.widthEdit, self.heightEdit)
        MainWindow.setTabOrder(self.heightEdit, self.ratioCheckBox)
        MainWindow.setTabOrder(self.ratioCheckBox, self.resizeButton)
        MainWindow.setTabOrder(self.resizeButton, self.saveButton)
        MainWindow.setTabOrder(self.saveButton, self.imageScrollArea)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Resizer"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.heightLabel.setText(_translate("MainWindow", "Height"))
        self.widthLabel.setText(_translate("MainWindow", "Width"))
        self.resizeButton.setText(_translate("MainWindow", "Resize"))
        self.inputFileButton.setText(_translate("MainWindow", "Choose Input"))
        self.ratioCheckBox.setText(_translate("MainWindow", "Preserve Aspect Ratio"))
